<?php
/**
 * TicketRoom default settings. Never served to visitors.
 *
 * Do not edit this file on the server: the next upload of the site replaces
 * it. Your own settings (the mailbox password, for example) go in
 * data/config.php, which the site creates the first time it opens and which
 * no upload ever touches. Anything set there wins over what is here.
 */
return [
    // The address of the site, used in emails. Leave as is unless the domain changes.
    'baseUrl' => 'https://ticketroom.co.za',

    /*
     * The first administrator, created the first time the site is opened.
     * The password is stored as a one-way hash, never as plain text. Sign in
     * at https://ticketroom.co.za/signin with the temporary password you were
     * given, then change it under My account → Settings. The back office
     * reminds you until you do.
     *
     * Changing this later does nothing on a live site, because the account
     * already exists. To reset a forgotten password, see START-HERE.txt.
     */
    'admin' => [
        'email' => 'hello@ticketroom.co.za',
        'name' => 'TicketRoom Admin',
        'passwordHash' => '{{ADMIN_PASSWORD_HASH}}',
    ],

    // Email: the hosting server's built-in mail until a mailbox password is
    // set in data/config.php, then the mailbox itself.
    'mail' => [
        'mode' => 'auto',
        'smtpHost' => 'mail.ticketroom.co.za',
        'smtpPort' => 465,
        'smtpUser' => 'hello@ticketroom.co.za',
        'smtpPass' => '',
        'fromEmail' => 'hello@ticketroom.co.za',
        'fromName' => 'TicketRoom',
    ],

    // Fees: R10 per paid ticket to the buyer, 5% commission to the organiser.
    // Free tickets carry no fees.
    'fees' => ['ticketFeeFixedCents' => 1000, 'ticketFeeBps' => 0, 'organiserCommissionBps' => 500],

    // Optional: an Anthropic API key lets the website assistant answer in its
    // own words. Without one it answers from the help articles.
    'anthropicApiKey' => '',
    'chatbotModel' => 'claude-opus-5-5',
    'chatbotDailyLimit' => 300,
];
